---

- name: Deploying app
  hosts: ec2
  connection: ssh

  tasks:
  - name: Copying docker-compose file
    copy: src=app1/docker-compose.yml dest=~/home/ubuntu/
 
  - name: Copying env file
    copy: src=app1/.env dest=~/home/ubuntu/
 

  - name: Running docker-compose.yml
    command: sudo docker-compose -f ~/home/ubuntu/docker-compose.yml up -d

  - name: Removing docker compose file
    command: sudo rm -f ~/home/ubuntu/docker-compose.yml 

