---

- name: Configure EC2 instance
  hosts: ec2
  connection: ssh
  sudo: true


  tasks:
  - name: Update the machine
    command: sudo apt-get update
    
  - name: Installing essentials
    command: sudo apt-get install apt-transport-https ca-certificates curl -y
      
  - name: Installing keyserver
    command: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  
  - name: adding deb to lists
    command: echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
  
  - name: update machine again
    command: sudo apt-get update
 
  - name: adding cache policy for docker-engine
    command: apt-cache policy docker-engine
 
  - name: Adding user to group
    command: sudo usermod -aG docker ${USER}

  - name: installing docker-engine
    command: sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
    command: sudo apt-get install docker-engine

  - name: Restarting docker service
    command: sudo service docker restart 

  - name: Updating the machine 2
    command: sudo apt-get update

  - name: Installing Python Pip
    command: sudo apt-get install python-pip python-dev build-essential -y

  - name: Installing Docker compose part
    command:  curl -L "https://github.com/docker/compose/releases/download/1.8.1/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose
    command: chmod +x /usr/local/bin/docker-compose 
    
  - name: apt update
    apt: update_cache=yes cache_valid_time=3600
    register: apt_result
    until: apt_result|success
    retries: 3
    delay: 1
    sudo: yes
    ignore_errors: yes

  - name: retry if needed using command apt-get update
    command: apt-get update
    sudo: yes
    when: apt_result|failed
    
