---
### provision AWS VPC
- hosts: localhost
  connection: local
  gather_facts: false
  user: root

  vars_files:
    - info/aws-credentials.yml
    - info/specs.yml

  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ aws_region }}"
        state: "present"
        ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      register: my_vpc


    - name: sleep for 30 seconds and continue with play
      wait_for: timeout=30
      delegate_to: localhost

    - name: Set VPC ID in variable
      set_fact:
        vpc_id: "{{ my_vpc.vpc.id }}"
        ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"

    - name: Create Public Subnet
      ec2_vpc_subnet:
        state: "present"
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ public_subnet_1_cidr }}"
        az: "{{ aws_region }}a"
        region: "{{ aws_region }}"
        resource_tags:
          Name: "Public Subnet"
        ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      register: my_public_subnet

    - name: Set Public Subnet ID in variable
      set_fact:
        public_subnet_id: "{{ my_public_subnet.subnet.id }}"
      ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"


    - name: Create Internet Gateway for VPC
      ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: "present"
        ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      register: my_vpc_igw


    - name: Set Internet Gateway ID in variable
      set_fact:
        igw_id: "{{ my_vpc_igw.gateway_id }}"
        ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        tags:
          Name: "Public"
        subnets:
          - "{{ public_subnet_id }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw_id }}"
        ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"

    - name: Create Main Security Group
      ec2_group:
        name: "My Security Group"
        description: "My Security Group"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: "tcp"
            from_port: "22"
            to_port: "22"
            cidr_ip: "{{ my_ip_range }}"
        ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      register: my_vpc_sg

    - name: Set Security Group ID in variable
      set_fact:
        sg_id: "{{ my_vpc_sg.group_id }}"
      ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
